name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Windows Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXT_PUBLIC_FIREBASE_API_KEY: "dummy-key"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "dummy-domain.firebaseapp.com"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "dummy-project"
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "dummy-project.appspot.com"
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "123456789"
        NEXT_PUBLIC_FIREBASE_APP_ID: "1:123456789:web:dummy"
      run: npm run dist:win

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: dist/

  create-release:
    needs: release
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Display structure
      run: ls -la
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.exe
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}